apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  commonName: mycompagny.com
  secretName: argocd-cert
  dnsNames:
    - mycompagny.com
  issuerRef:
    name: letsencrypt-prod # letsencrypt-prod
    kind: ClusterIssuer
